// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: interface/grpc/proto/feromona.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeromonaLBH struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodo          string                 `protobuf:"bytes,1,opt,name=nodo,proto3" json:"nodo,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Firma         string                 `protobuf:"bytes,3,opt,name=firma,proto3" json:"firma,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeromonaLBH) Reset() {
	*x = FeromonaLBH{}
	mi := &file_interface_grpc_proto_feromona_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeromonaLBH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeromonaLBH) ProtoMessage() {}

func (x *FeromonaLBH) ProtoReflect() protoreflect.Message {
	mi := &file_interface_grpc_proto_feromona_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeromonaLBH.ProtoReflect.Descriptor instead.
func (*FeromonaLBH) Descriptor() ([]byte, []int) {
	return file_interface_grpc_proto_feromona_proto_rawDescGZIP(), []int{0}
}

func (x *FeromonaLBH) GetNodo() string {
	if x != nil {
		return x.Nodo
	}
	return ""
}

func (x *FeromonaLBH) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *FeromonaLBH) GetFirma() string {
	if x != nil {
		return x.Firma
	}
	return ""
}

func (x *FeromonaLBH) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type FeromonaRespuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Nodo          string                 `protobuf:"bytes,3,opt,name=nodo,proto3" json:"nodo,omitempty"`
	Payload       string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Ts            int64                  `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeromonaRespuesta) Reset() {
	*x = FeromonaRespuesta{}
	mi := &file_interface_grpc_proto_feromona_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeromonaRespuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeromonaRespuesta) ProtoMessage() {}

func (x *FeromonaRespuesta) ProtoReflect() protoreflect.Message {
	mi := &file_interface_grpc_proto_feromona_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeromonaRespuesta.ProtoReflect.Descriptor instead.
func (*FeromonaRespuesta) Descriptor() ([]byte, []int) {
	return file_interface_grpc_proto_feromona_proto_rawDescGZIP(), []int{1}
}

func (x *FeromonaRespuesta) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FeromonaRespuesta) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FeromonaRespuesta) GetNodo() string {
	if x != nil {
		return x.Nodo
	}
	return ""
}

func (x *FeromonaRespuesta) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *FeromonaRespuesta) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_interface_grpc_proto_feromona_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_interface_grpc_proto_feromona_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_interface_grpc_proto_feromona_proto_rawDescGZIP(), []int{2}
}

var File_interface_grpc_proto_feromona_proto protoreflect.FileDescriptor

const file_interface_grpc_proto_feromona_proto_rawDesc = "" +
	"\n" +
	"#interface/grpc/proto/feromona.proto\x12\x03lbh\"a\n" +
	"\vFeromonaLBH\x12\x12\n" +
	"\x04nodo\x18\x01 \x01(\tR\x04nodo\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x14\n" +
	"\x05firma\x18\x03 \x01(\tR\x05firma\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"\x7f\n" +
	"\x11FeromonaRespuesta\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04nodo\x18\x03 \x01(\tR\x04nodo\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12\x0e\n" +
	"\x02ts\x18\x05 \x01(\x03R\x02ts\"\a\n" +
	"\x05Vacio2\x86\x01\n" +
	"\x0fFeromonaService\x12:\n" +
	"\x0eEmitirFeromona\x12\x10.lbh.FeromonaLBH\x1a\x16.lbh.FeromonaRespuesta\x127\n" +
	"\x0fListarFeromonas\x12\n" +
	".lbh.Vacio\x1a\x16.lbh.FeromonaRespuesta0\x01B*Z(lbh-node-service/interface/grpc/genprotob\x06proto3"

var (
	file_interface_grpc_proto_feromona_proto_rawDescOnce sync.Once
	file_interface_grpc_proto_feromona_proto_rawDescData []byte
)

func file_interface_grpc_proto_feromona_proto_rawDescGZIP() []byte {
	file_interface_grpc_proto_feromona_proto_rawDescOnce.Do(func() {
		file_interface_grpc_proto_feromona_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interface_grpc_proto_feromona_proto_rawDesc), len(file_interface_grpc_proto_feromona_proto_rawDesc)))
	})
	return file_interface_grpc_proto_feromona_proto_rawDescData
}

var file_interface_grpc_proto_feromona_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_interface_grpc_proto_feromona_proto_goTypes = []any{
	(*FeromonaLBH)(nil),       // 0: lbh.FeromonaLBH
	(*FeromonaRespuesta)(nil), // 1: lbh.FeromonaRespuesta
	(*Vacio)(nil),             // 2: lbh.Vacio
}
var file_interface_grpc_proto_feromona_proto_depIdxs = []int32{
	0, // 0: lbh.FeromonaService.EmitirFeromona:input_type -> lbh.FeromonaLBH
	2, // 1: lbh.FeromonaService.ListarFeromonas:input_type -> lbh.Vacio
	1, // 2: lbh.FeromonaService.EmitirFeromona:output_type -> lbh.FeromonaRespuesta
	1, // 3: lbh.FeromonaService.ListarFeromonas:output_type -> lbh.FeromonaRespuesta
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interface_grpc_proto_feromona_proto_init() }
func file_interface_grpc_proto_feromona_proto_init() {
	if File_interface_grpc_proto_feromona_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interface_grpc_proto_feromona_proto_rawDesc), len(file_interface_grpc_proto_feromona_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_interface_grpc_proto_feromona_proto_goTypes,
		DependencyIndexes: file_interface_grpc_proto_feromona_proto_depIdxs,
		MessageInfos:      file_interface_grpc_proto_feromona_proto_msgTypes,
	}.Build()
	File_interface_grpc_proto_feromona_proto = out.File
	file_interface_grpc_proto_feromona_proto_goTypes = nil
	file_interface_grpc_proto_feromona_proto_depIdxs = nil
}
