// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: interface/grpc/proto/feromona.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FeromonaService_EmitirFeromona_FullMethodName  = "/lbh.FeromonaService/EmitirFeromona"
	FeromonaService_ListarFeromonas_FullMethodName = "/lbh.FeromonaService/ListarFeromonas"
)

// FeromonaServiceClient is the client API for FeromonaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeromonaServiceClient interface {
	EmitirFeromona(ctx context.Context, in *FeromonaLBH, opts ...grpc.CallOption) (*FeromonaRespuesta, error)
	ListarFeromonas(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FeromonaRespuesta], error)
}

type feromonaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFeromonaServiceClient(cc grpc.ClientConnInterface) FeromonaServiceClient {
	return &feromonaServiceClient{cc}
}

func (c *feromonaServiceClient) EmitirFeromona(ctx context.Context, in *FeromonaLBH, opts ...grpc.CallOption) (*FeromonaRespuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeromonaRespuesta)
	err := c.cc.Invoke(ctx, FeromonaService_EmitirFeromona_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feromonaServiceClient) ListarFeromonas(ctx context.Context, in *Vacio, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FeromonaRespuesta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FeromonaService_ServiceDesc.Streams[0], FeromonaService_ListarFeromonas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Vacio, FeromonaRespuesta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeromonaService_ListarFeromonasClient = grpc.ServerStreamingClient[FeromonaRespuesta]

// FeromonaServiceServer is the server API for FeromonaService service.
// All implementations must embed UnimplementedFeromonaServiceServer
// for forward compatibility.
type FeromonaServiceServer interface {
	EmitirFeromona(context.Context, *FeromonaLBH) (*FeromonaRespuesta, error)
	ListarFeromonas(*Vacio, grpc.ServerStreamingServer[FeromonaRespuesta]) error
	mustEmbedUnimplementedFeromonaServiceServer()
}

// UnimplementedFeromonaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFeromonaServiceServer struct{}

func (UnimplementedFeromonaServiceServer) EmitirFeromona(context.Context, *FeromonaLBH) (*FeromonaRespuesta, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitirFeromona not implemented")
}
func (UnimplementedFeromonaServiceServer) ListarFeromonas(*Vacio, grpc.ServerStreamingServer[FeromonaRespuesta]) error {
	return status.Error(codes.Unimplemented, "method ListarFeromonas not implemented")
}
func (UnimplementedFeromonaServiceServer) mustEmbedUnimplementedFeromonaServiceServer() {}
func (UnimplementedFeromonaServiceServer) testEmbeddedByValue()                         {}

// UnsafeFeromonaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeromonaServiceServer will
// result in compilation errors.
type UnsafeFeromonaServiceServer interface {
	mustEmbedUnimplementedFeromonaServiceServer()
}

func RegisterFeromonaServiceServer(s grpc.ServiceRegistrar, srv FeromonaServiceServer) {
	// If the following call panics, it indicates UnimplementedFeromonaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FeromonaService_ServiceDesc, srv)
}

func _FeromonaService_EmitirFeromona_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeromonaLBH)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeromonaServiceServer).EmitirFeromona(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FeromonaService_EmitirFeromona_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeromonaServiceServer).EmitirFeromona(ctx, req.(*FeromonaLBH))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeromonaService_ListarFeromonas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Vacio)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FeromonaServiceServer).ListarFeromonas(m, &grpc.GenericServerStream[Vacio, FeromonaRespuesta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FeromonaService_ListarFeromonasServer = grpc.ServerStreamingServer[FeromonaRespuesta]

// FeromonaService_ServiceDesc is the grpc.ServiceDesc for FeromonaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FeromonaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lbh.FeromonaService",
	HandlerType: (*FeromonaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitirFeromona",
			Handler:    _FeromonaService_EmitirFeromona_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListarFeromonas",
			Handler:       _FeromonaService_ListarFeromonas_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "interface/grpc/proto/feromona.proto",
}
